apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chat
  labels:
    app: go-chat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-chat
  template:
    metadata:
      labels:
        app: go-chat
    spec:
      containers:
        - name: go-chat
          image: ghcr.io/slotje/go-chat-main-eindopdracht:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-chat-service
spec:
  selector:
    app: go-chat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-chat-ingress
spec:
  rules:
    - host: go-chat.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-chat-service
                port:
                  number: 80