apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-chat-app
  namespace: go-chat-namespace
  labels:
    app: go-chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-chat-app
  template:
    metadata:
      labels:
        app: go-chat-app
    spec:
      containers:
        - name: go-chat-container
          image: ghcr.io/Slotje/go-chat-main:latest
          ports:
            - containerPort: 8080