apiVersion: v1
kind: Service
metadata:
  name: go-chat-service
  namespace: go-chat-namespace
spec:
  selector:
    app: go-chat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer