docker:
  name: Build and Push Docker Image
  needs: build
  runs-on: ubuntu-latest
  outputs:
    image_name: ${{ steps.set_image.outputs.image_name }}
  permissions:
    contents: read
    packages: write

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image name
      id: set_image
      run: |
        IMAGE_NAME_LOWER=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        echo "image_name=${IMAGE_NAME_LOWER}:latest" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t ${{ steps.set_image.outputs.image_name }} .

    - name: Push Docker image
      run: docker push ${{ steps.set_image.outputs.image_name }}